### ISSUE TITLE
Allow more hospitals per workplace

### ISSUE THREAD

**Issue by aneeque1986** [anaestheticsapp/logbook#22]
I work in 4 different hospitals but at a time only 2 hoapital name came kindly make feature so that different hospital can be selected 
Dr . M. Aneeque Alam
Karachi Pakistan.

**Comment by anaestheticsapp** [comment]
Thanks for the feedback, I will try and implement something with the next update

**Comment by anaestheticsapp** [comment]
- [x] Add form validation
- [x] Empty end place will result to default
- [x] Update database tables
- [x] Test edit workplace and add create new workplace
- [x] Test delete workplace
- [x] Test input form
- [x] Test filters
- [x] Test iOS
- [x] Push out to Google Play Store
- [x] Push out to Progressive Web App

**Comment by anaestheticsapp** [comment]
This has now been pushed out to all devices as a minor update (due to popular demand). When editing or creating a new workplace, click on "Add more hospitals". You can now select another 3 hospitals (total of 4). Will be officially announced with the next major update in September/October.

**Comment by aneeque1986** [comment]
Thank you👍😁
