### ISSUE TITLE
preselect appropriate "session" radioelement

### ISSUE THREAD

**Issue by leoric23** [anaestheticsapp/logbook#56]
i usually add cases on the go in the OR. it would be convenient if the radio boxes for the time of day would preselect the proper element according to the actual time. cheers!

**Comment by anaestheticsapp** [comment]
Good idea, thanks. Will be testing the new update all of next week and hopefully release this, so can only start working ont his after.

**Comment by anaestheticsapp** [comment]
Pushed with latest minor update (25.1.19)

This feature is disabled by default. To enable,
* Go to the input form / insert case
* Click on Settings button
* In the new Form Settings card, enable "Prefill Session"

Session will now be prefilled if date selected is "Today".

Not enabled by default as most users tend to enter cases at the end of the day
Changing session would need two clicks here (ie when entering cases from morning in evening, user must deselect Evening and select Morning).
