### ISSUE TITLE
Downloading PDF

### ISSUE THREAD

**Issue by jbalmforth17** [anaestheticsapp/logbook#58]
Hi Simon,
When trying to download a PDF file of events/teaching it gets stuck on a wheel of doom which says “Downloading PDF file…”, have tried it on multiple devices with the same issue. 

Thanks!

![9D4C6D0A-0C4E-42F2-84FD-669132B91BD4](https://user-images.githubusercontent.com/88199099/127667329-e14301a0-9db0-4017-9375-73ca939ad7eb.jpeg)

**Comment by anaestheticsapp** [comment]
Ah yes that's broken, sorry! Fixed with latest update (25.1.19)
